<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateMediaTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('media', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('media_category_id');
            $table->unsignedInteger('model_id');
            $table->string('model_type', 255);
            $table->string('collection_name', 255);
            $table->string('name', 255);
            $table->text('description')->nullable();
            $table->string('file_name', 255)->nullable();;
            $table->string('file_ext', 255)->nullable();;
            $table->string('disk', 255)->nullable();;
            $table->unsignedInteger('size')->nullable();;
            $table->text('manipulations')->nullable();;
            $table->boolean('pub')->nullable()->default(1);
            $table->unsignedInteger('sort')->nullable();
            $table->integer('created_by')->nullable();
            $table->integer('updated_by')->nullable();
            $table->timestamps();
          });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('media');
    }
}
